### ISSUE TITLE
Lỗi không get được /api/session/download

### ISSUE THREAD

**Issue by tuannt23065** [tudoanh/get_fshare#13]
Như tiêu đề hiện tại api get download không dùng được nữa, hy vọng là có fix, cảm ơn @tudoanh 

<img width="411" alt="Screen Shot 2020-09-25 at 07 13 16" src="https://user-images.githubusercontent.com/57710664/94212586-c8121d00-fefe-11ea-9bad-13eb29daf547.png">

**Comment by kyocooro** [comment]
> 
> 
> Như tiêu đề hiện tại api get download không dùng được nữa, hy vọng là có fix, cảm ơn @tudoanh
> 
> <img alt="Screen Shot 2020-09-25 at 07 13 16" width="411" src="https://user-images.githubusercontent.com/57710664/94212586-c8121d00-fefe-11ea-9bad-13eb29daf547.png">

đổi User-Agent tại dòng 21 file get_fshare.py là được. 
self.s.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0'

**Comment by tudoanh** [comment]
Nếu bạn đã sửa và test ok thì có thể tạo PR nhé, tại dạo này mình cũng ít
maintain project này

Vào Th 7, 5 thg 12, 2020 lúc 23:58 kyocooro <notifications@github.com> đã
viết:
