### ISSUE TITLE
Xin hỏi cách lấy API của Fshare

### ISSUE THREAD

**Issue by tyrion9** [tudoanh/get_fshare#16]
Xin hỏi anh @tudoanh làm sao anh lấy được API của FShare mà hay quá? Cách anh lấy thế nào đấy ạ? API này chắc của FShare Tool chứ không phải của web mà FShare cũng không public API ra. Xem mấy chỗ thì của anh là đầy đủ nhất.

**Comment by tudoanh** [comment]
Anh lấy bên app android của Fshare, nhưng app đã ngừng update từ 2018, và đến giờ API chắc cũng ko hoạt động được nữa. Đợi bao giờ app update thì anh sẽ update lại lib này.
