### ISSUE TITLE
Question about fshare API

### ISSUE THREAD

**Issue by farOverNinethousand** [tudoanh/get_fshare#4]
Hi,
do you know whether the fshare API also has a call which returns information about accounts such as "ViP" or "Free" or the expire-date?
I was not able to find out anything but this would be really useful for an application I'am contributing to (JDownloader).

Best regards

**Comment by tudoanh** [comment]
I've added the method `profile`.  
You should use it to check VIP status of the account (FYI: `'expire_vip'` not equal 0)

**Comment by farOverNinethousand** [comment]
Thanks - that works!

By the way, expire_vip may even be > 0 but the account can be an expired premium account.
You have to check it against the current date to find out whether it is a premium account or not.
Example of a real account:
`{
  "id": "000000",
  "level": "2",
  "name": "CENSORED",
  "phone": "",
  "birthday": "0000-00-00",
  "gender": null,
  "address": "",
  "id_card": null,
  "city": "CENSORED",
  "occupation": "",
  "email": "CENSORED",
  "joindate": "1491814900",
  "totalpoints": "CENSORED",
  "expire_vip": "1557546640",
  "traffic": "0",
  "traffic_used": "0",
  "webspace": "0",
  "webspace_used": "0",
  "webspace_secure": "0",
  "webspace_secure_used": "\r\n10000000",
  "amount": "0",
  "dl_time_avail": "0",
  "status_telesale_prepaid": "0",
  "account_type": "Member"
}`
