### ISSUE TITLE
Package does not work anymore

### ISSUE THREAD

**Issue by nguyenph88** [tudoanh/get_fshare#6]
Hi,

Look like the package does not work anymore. If you try to simply run "pytest", it will result in the malformed json as there is no json in the return. Switching your test account to my current VIP user does not work either.

I took your request sample and use Postman, sending it along with email, password (VIP user) and your app_key, but received an "internal server error", sometimes 403. That's the actual result when using your package, I keep getting 403 error. 

Can you please check? Thanks.

**Comment by tudoanh** [comment]
Seem like the Fshare app's pinning SSL strategy was changed, I'm working on it to bypass that.

**Comment by nguyenph88** [comment]
any updates on this? Thanks

**Comment by farOverNinethousand** [comment]
Also, it seems like they have disabled HTTP 1.1 support for API requests?!
With HTTP 1.1, it will always return error 500.

Can anyone confirm that?

**Comment by tudoanh** [comment]
Nah, they use SSL pinning to prevent their API being exposed. I’m still
working on it.

Vào Th 7, 5 thg 10, 2019 lúc 23:33 farOverNinethousand <
notifications@github.com> đã viết:

**Comment by farOverNinethousand** [comment]
I've checked it via Android App "Http Canary" and it looks just like before.
I'am still able to login with the same request but not via HTTP 1.X anymore - only HTTP 2.

Thanks for keeping it up!

**Comment by tudoanh** [comment]
Let's me check on that HTTP 2 solution. Thanks.

**Comment by tudoanh** [comment]
Damn, that's correct! I will update ASAP.

**Comment by tudoanh** [comment]
Update and fixed.
