### ISSUE TITLE
Return 405 [Method not allowed]

### ISSUE THREAD

**Issue by M15t** [tudoanh/get_fshare#7]
<img width="968" alt="Screen Shot 2019-10-17 at 1 19 48 AM" src="https://user-images.githubusercontent.com/8831533/66946989-440fae00-f07c-11e9-94c7-cfa7597732c2.png">

I assume that they have changed request method. Do you got anything news?

**Comment by tudoanh** [comment]
Yes, just use HTTP 2 for authentication API. See my updated code for example.

**Comment by M15t** [comment]
So funny thing is this one not the root cause lol
I have entered wrong pwd and their APIs return status code 405 lmao
